### ISSUE TITLE
Failed to compile entry-point @codebakery/origami/styles (module as esm5) due to compilation errors

### ISSUE THREAD

**Issue by nagarajhubli** [hotforfeature/origami#101] opened 2020-03-27 09:05 UTC
I am building a demo app to showcase usage of Polymer 3.x with Angular 9.x, and I am getting the following error while building

```
ERROR in Failed to compile entry-point @codebakery/origami/styles (module as esm5) due to compilation errors:
node_modules/@codebakery/origami/fesm5/origami-styles.js:587:24 - error NG2005: The class 'ShadyCSSSharedStylesHost' cannot be created via dependency injection, as it does not have an Angular decorator. This will result in an error at runtime.

Either add the @Injectable() decorator to 'ShadyCSSSharedStylesHost', or configure a different provider (such as a provider with 'useFactory').


587             providers: [SHADYCSS_SHARED_STYLES_HOST_PROVIDER]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@codebakery/origami/fesm5/origami-styles.js:501:5
    501 var ShadyCSSSharedStylesHost = /** @class */ (function (_super) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    502     __extends(ShadyCSSSharedStylesHost, _super);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ... 
    542     return ShadyCSSSharedStylesHost;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    543 }(ɵDomSharedStylesHost));
        ~~~~~~~~~~~~~~~~~~~~~~~~
    'ShadyCSSSharedStylesHost' is declared here.

```
Angular version is 9.1.0
Polymer version is 3.3.1
Origami version is 3.1.2

Node - v12.0.0
NPM - 6.9.0

**Comment by nagarajhubli** [comment] 2020-03-27 09:16
The application builds fine if I opt out of the default Ivy engine which comes with Angular 9.x, followed the instructions from here - https://angular.io/guide/ivy#opting-out-of-ivy-in-version-9

**Comment by asyncLiz** [comment] 2020-03-27 17:42
Duplicate of https://github.com/hotforfeature/origami/issues/99. Origami does not yet support Angular 9 or Ivy, but I'm happy to accept a PR adding it!

**Closed by asyncLiz** 2020-03-27 17:42 UTC
